# Generated by Django 6.0.2 on 2026-03-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_seedforce_alter_skill_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('bad_code', models.TextField()),
                ('good_code', models.TextField()),
            ],
        ),
    ]
