# Generated by Django 6.0.2 on 2026-03-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_wisdomtip_battle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedforce',
            name='value',
            field=models.IntegerField(default=100),
        ),
    ]
